# Generated by Django 3.1.4 on 2020-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat_user', '0002_auto_20201225_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
