# Generated by Django 3.1.2 on 2021-01-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat_user', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='martial_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
