# Generated by Django 3.1.2 on 2021-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat_user', '0007_auto_20210115_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_uploaded',
            field=models.FileField(default='', upload_to='video/'),
        ),
    ]
