# Generated by Django 3.1.2 on 2021-02-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat_user', '0009_auto_20210122_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
