# Generated by Django 3.1.2 on 2021-02-07 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat_user', '0011_auto_20210205_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
